import fs from "fs";
import path from "path";
import { scanRoutes, RouteInfo } from "./routing";

export function buildGeneratedRoutes(appDir: string) {
  const routesDir = path.join(appDir, "src/routes");
  const outFile = path.join(appDir, "src/generated-routes.ts");

  if (!fs.existsSync(routesDir)) {
    fs.writeFileSync(outFile, "export const routes = {};", "utf-8");
    return;
  }

  const routeMap = scanRoutes(routesDir);

  const entries: string[] = [];
  for (const [route, info] of Object.entries(routeMap)) {
    const layoutsArray = `[${info.layouts.map(l => `() => import("${l}")`).join(", ")}]`;
    entries.push(`  "${route}": { page: () => import("${info.page}"), layouts: ${layoutsArray}${info.noLayout ? ", noLayout: true" : ""} }`);
  }

  const content = `// Auto-generated by Clarity preprocessor
export const routes = {
${entries.join(",\n")}
};
`;

  fs.writeFileSync(outFile, content, "utf-8");
}
